CREATE TABLE tasks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(100)             NOT NULL,
    description VARCHAR,
    status      VARCHAR(20)              NOT NULL,
    due_date    DATE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_tasks_status ON tasks (status);
