CREATE TABLE short_links (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(8)               NOT NULL,
    original_url VARCHAR(2048)            NOT NULL,
    visit_count  BIGINT                   NOT NULL DEFAULT 0,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at   TIMESTAMP WITH TIME ZONE,
    -- The real uniqueness guarantee for codes: concurrent inserts of the same code cannot both succeed.
    CONSTRAINT uk_short_links_code UNIQUE (code)
);
