CREATE TABLE products (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(200)             NOT NULL,
    category   VARCHAR(50)              NOT NULL,
    price      DECIMAL(10, 2)           NOT NULL,
    stock      INT                      NOT NULL,
    rating     DECIMAL(2, 1)            NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_products_price CHECK (price >= 0),
    CONSTRAINT ck_products_stock CHECK (stock >= 0),
    CONSTRAINT ck_products_rating CHECK (rating BETWEEN 0 AND 5)
);

-- Support the category filter, the price-range filter and the most common sorts.
CREATE INDEX idx_products_category ON products (category);
CREATE INDEX idx_products_price ON products (price);
CREATE INDEX idx_products_created_at ON products (created_at);
