CREATE TABLE orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer        VARCHAR(254)             NOT NULL,
    status          VARCHAR(20)              NOT NULL,
    idempotency_key VARCHAR(64)              NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_orders_status CHECK (status IN ('PLACED', 'CANCELLED')),
    -- Recognises a retry: the same customer can never store two orders under one key, even when
    -- both requests run at the same moment (the second INSERT fails and its transaction rolls back).
    CONSTRAINT uq_orders_customer_idempotency_key UNIQUE (customer, idempotency_key)
);

CREATE TABLE order_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT         NOT NULL,
    product_id BIGINT         NOT NULL,
    quantity   INT            NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_order_items_quantity CHECK (quantity > 0)
);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);
